language: java
jdk:
- openjdk8
sudo: required
services:
- docker
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
addons:
  apt:
    packages:
    - expect
    - rpm
    - gnupg
stages:
- name: build
- name: test
- name: upgrade-test
  if: tag IS blank
- name: sign
jobs:
  include:
  - stage: build
    script: "./gradlew clean build"
  - stage: test
    env: JOB='deb/rpm install test'
    script: bash scripts/install-test.sh
  - stage: upgrade-test
    env: JOB='rpm upgrade test'
    script: bash scripts/rpm-upgrade.sh
  - stage: sign
    if: fork = false AND type = push AND tag =~ ^v
    env: JOB='rpm signing'
    script:
    - test -d $HOME/.gnupg || mkdir $HOME/.gnupg
    - openssl aes-256-cbc -K $encrypted_168997f84686_key -iv $encrypted_168997f84686_iv
      -in gpg.tar.enc -out gpg.tar -d
    - test -f gpg.tar && tar xv -C $HOME/.gnupg -f gpg.tar
    - test -f $HOME/.gnupg/secring.gpg && GPG_PATH=$HOME/.gnupg ./travis-sign-rpm.sh
      rd-cli-tool/build/distributions
deploy:
  provider: releases
  api_key:
    secure: E5dKfiXBUTFpIJFWSk2+jBcS6FdO++DHqqGp8XDtrrCpKJfynYqPR+/23oYKYVz+H21CnEiUTqtVKvlftccWbErcRAD3R0G1bw6efj3TNiBb0Z0dRa8qgP+3NVTWhRZ4hwSn/0mClY96kz3cEjiJlBs6lYgneKlmg2As++LDjGIWZEfPUBXK6gtG69ZtMj2NBibKg1KQWZV6nZApBvYtkGJJqhu82jlDMbi5ltaOayVl4ISy0NlfcyW9ZNeLsCgjq9NVl5UV7ti6wB25fosz3fc7OZVF0SlU7Txg5Gi0bsnvRAijZRpZQwuo0Dza3Tqv6YDTXmfZT8qaqF6+SGNBH1BLSVApk2pBddJATzM5o0SZkuywUK4tMq6qCJjdPgMXnR4b/t3jK5f5w/ahWgYsqU7z7dBpxDDWafDFibkylJEQaUexktYdxq7JQZ5F6CNcT+qkPhj6LELR9eYh22xnuorwh6sfBfQqWJ0zveD9IcAv4Fl0ogXniftaLxRJ+G9vSQtzruWCTQRT3Ys2eIjc67wI47uMFcU5naM/YDt9BAQZzBoP9vKGiiyRwoa5kqpEy++qtod8oQTN1mw0B3BubrtlDAKirp8S+Zoix7EAvBt0abIO+zOvblUAjzb4zf2DxXkakvWZ4hxq8LnOItxItyBBRbDxiNYigYd8lRW0los=
  file:
  - rd-cli-tool/build/distributions/rd-*.zip
  - rd-cli-tool/build/distributions/rundeck-cli*.rpm
  - rd-cli-tool/build/distributions/rundeck-cli*.deb
  - rd-cli-tool/build/libs/rundeck-cli-*-all.jar
  - rd-api-client/build/libs/rd-api-client-*.jar
  - rd-cli-lib/build/libs/rd-cli-lib-*.jar
  on:
    repo: rundeck/rundeck-cli
    tags: true
  file_glob: true
  skip_cleanup: true
env:
  global:
  - secure: 2LDWRCZsuUYNUNHQz4oiaq9VIcdp0ziI7SKBxUxfqT4rehJ0J7kz+UPqwtgxMiUyQaHJQqzkcR+m6H3VZj9BREY+POiyu+yJOqhe3KRpDAfiN/gnwN81Nh9wloVaxyVe6i5yPaaBvE5vIREi7SAUdDtdsQ6WSkQ3JnaSL5Nz6e3DKR6+wgaTmBhh/TTW1YuN1qo5EjBpm0//M+KwY5BvVYOfPYLHCpVqnWFePQBkZY13lvufC5XPipXMf6c5Un/Uy6oVaRgLSPHDyELQvBzMSRPtzNmJSDm75LvclHHgDYEUcrcxRoWgAEISaBeIpGhe/PnsswCtQMfQBIm0W8Cv+HThbdCrrTdz/hWsohVvLFkCl9L8NOTOnATr2I9F0GBmsdhJvvr10JqGGol8Y9wwu5eiO9AWmchjZPicIWj5Dwo9E8AdT20aX4l287StESedS/Wtqh7gdf4d3Y1svWLEmh3gbERqOI9hRDV0DotfumhaW49SbaN/XecODiyPrnLBONSrYk1bWADDAvBZm/Jy0hvFbaVFFI8HfZMVJCO4GJJwna2MEMnsouNl2eDBFtvX5JHQ00JP4QacPFwW3/0NsgdaUGLiPSNezNJ1kBYtVbhQg4oL3yTkFaU6KuGhJcdSCVJUwOeP0YZF0oklofLhEhc4puzAi6EmGvLpMeh/huw=
