name: Publish tag release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Push events to matching semver 20.15.10

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Sign RPM and Deb
        run: |
          test -d $HOME/.gnupg || mkdir $HOME/.gnupg
          GPG_PATH=$HOME/.gnupg ./travis-sign-rpm.sh rd-cli-tool/build/distributions
        env:
          SIGNING_KEY_B64: ${{ secrets.SIGNING_KEY_B64 }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEYID: build@rundeck.org
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: |
            rd-cli-tool/build/distributions/rd-*.zip
            rd-cli-tool/build/distributions/rundeck-cli-*-1.noarch.rpm
            rd-cli-tool/build/distributions/rundeck-cli_*-1_all.deb
            rd-cli-tool/build/libs/rundeck-cli-*-all.jar
            rd-api-client/build/libs/rd-api-client-*.jar
            rd-cli-lib/build/libs/rd-cli-lib-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Maven Central
        run: ./gradlew -PsigningKey=${SIGNING_KEY_B64} -PsigningPassword=${SIGNING_PASSWORD} -PsonatypeUsername=${SONATYPE_USERNAME} -PsonatypePassword=${SONATYPE_PASSWORD} publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY_B64: ${{ secrets.SIGNING_KEY_B64 }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
