name: Test homebrew update

on: workflow_dispatch

jobs:
   update_homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: trigger homebrew update
        # The PAT should have actions:read-write
        run: |
          curl -L \
            -X POST \
            --fail-with-body \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.HOMEBREW_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/rundeck/homebrew-rundeck-cli/actions/workflows/update.yml/dispatches \
            -d '{"ref":"main","inputs":{}}'
