name: Test package signing

on: workflow_dispatch

jobs:
  test-signing:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Install expect
        run: |
          sudo apt-get update -y
          sudo apt-get -y install expect dpkg-sig
      - name: Sign RPM and Deb
        run: |
          test -d $HOME/.gnupg || mkdir $HOME/.gnupg
          GPG_PATH=$HOME/.gnupg scripts/sign-packages.sh $PWD/rd-cli-tool/build/distributions
        env:
          SIGNING_KEY_B64: ${{ secrets.SIGNING_KEY_B64 }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEYID: signing@rundeck.com
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          # Directory containing files to upload
          path: |
            rd-cli-tool/build/distributions/*.rpm
            rd-cli-tool/build/distributions/*.deb
